name: pscc
description: Aplicativo Arquitetural
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.1.0
  brasil_fields: ^1.1.2
  cloud_firestore: ^2.1.0
  connectivity: ^3.0.4
  carousel_slider: ^4.0.0
  dio: ^4.0.0
  datetime_picker_formfield: ^2.0.0
  font_awesome_flutter: ^9.0.0
  firebase_core: ^1.0.3
  firebase_dynamic_links: ^2.0.4
  firebase_storage: ^8.0.3
  firebase_messaging: ^10.0.0
  firebase_auth: ^1.0.3
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_speed_dial: ^5.0.0+1
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  get: ^4.6.1
  get_storage: ^2.0.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  oktoast: ^3.0.0
  page_transition: ^2.0.5
  pay: ^1.0.3
  shimmer: ^2.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.6
  timelines: ^0.1.0
  url_launcher: ^6.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-yellow.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

scripts:
  gicon: flutter pub run flutter_launcher_icons:main